apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pcf-config
  labels:
    epc-mode: pcf
data:
  pcf.yaml: |
    logger:
        file: /var/log/open5gs/pcf.log
    
    db_uri: mongodb://{{ .Release.Name }}-mongodb-svc/open5gs

    pcf:
      sbi:
        - dev: eth0
          port: 443
          advertise: {{ .Release.Name }}-pcf.{{ .Release.Namespace }}.svc.cluster.local
      discovery:
         delegated: no           
    scp:
     sbi:
       - addr:
           - {{ .Release.Name }}-scp.{{ .Release.Namespace }}.svc.cluster.local
         port: 443
    nrf:
     sbi:
       - addr:
           - {{ .Release.Name }}-nrf.{{ .Release.Namespace }}.svc.cluster.local
         port: 443         
    sbi:
        server:
          cacert: /var/run/autocert.step.sm/root.crt
          key: /var/run/autocert.step.sm/site.key
          cert: /var/run/autocert.step.sm/site.crt
        client:
          cacert: /var/run/autocert.step.sm/root.crt
          key: /var/run/autocert.step.sm/site.key
          cert: /var/run/autocert.step.sm/site.crt