apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-smf
  labels:
    epc-mode: smf
spec:
  selector:
    epc-mode: smf
  ports:
    - protocol: TCP
      port: 443 
      targetPort: 443  
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-smf-deployment 
  labels:
    epc-mode: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: smf
  template:
    metadata:
      annotations:
        autocert.step.sm/name: {{ .Release.Name }}-smf.{{ .Release.Namespace }}.svc.cluster.local
        autocert.step.sm/duration: {{ .Values.certificate.duration }}        
      labels:
        epc-mode: smf
        epc-prom: enabled
    spec:
      serviceAccountName: {{ .Release.Name }}-k8s-wait-for
      initContainers:     
      - name: wait-for-scp
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=scp"
      - name: wait-for-upf
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=upf"
      - name: wait-for-nrf
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=nrf"                                
      containers:
      - name: smf
        image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
        imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
        ports:
        - containerPort: 9091
          name: prom
          protocol: TCP       
        command: ["/bin/sh", "-c"]
        args:
        - open5gs-smfd -c /open5gs/config-map/smf.yaml;
        volumeMounts:
          - name: {{ .Release.Name }}-smf-config
            mountPath: /open5gs/config-map/smf.yaml
            subPath: "smf.yaml"        
        securityContext:
           capabilities:
             add:
             - NET_ADMIN    
      volumes:
        - name: {{ .Release.Name }}-smf-config
          configMap:
            name: {{ .Release.Name }}-smf-config                
