apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-udm-config
  labels:
    epc-mode: udm
data:
  udm.yaml: |
    logger:
        file: /var/log/open5gs/udm.log

    udm:
      sbi:
        - dev: eth0
          port: 443
          advertise: {{ .Release.Name }}-udm.{{ .Release.Namespace }}.svc.cluster.local
      discovery:
         delegated: no           
    sbi:
        server:
          cacert: /var/run/autocert.step.sm/root.crt
          key: /var/run/autocert.step.sm/site.key
          cert: /var/run/autocert.step.sm/site.crt
        client:
          cacert: /var/run/autocert.step.sm/root.crt
          key: /var/run/autocert.step.sm/site.key
          cert: /var/run/autocert.step.sm/site.crt              
    scp:
     sbi:
       - addr:
           - {{ .Release.Name }}-scp.{{ .Release.Namespace }}.svc.cluster.local
         port: 443
    nrf:
     sbi:
       - addr:
           - {{ .Release.Name }}-nrf.{{ .Release.Namespace }}.svc.cluster.local
         port: 443         